apiVersion: v1
kind: Namespace
metadata:
  name: pedjasapp
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pedjasapp
type: Opaque
stringData:
  username: pedjas
  password: pedjas123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: pedjasapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: pedjasapp
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pedjasapp
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
